services:
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: compost-web
    restart: always
    env_file:
      - ./apps/web/.env.production
    depends_on:
      - db
    expose:
      - 3000
    networks:
      - default
      - web

  db:
    image: postgres:16-alpine
    container_name: compost-db
    restart: always
    env_file:
      - ./infra/db.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432

volumes:
  pgdata:

networks:
  web:
    external: true
